services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
