version: '3.5'

services:
  backend:
    build:
      context:
        ./backend
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - mongo
      - rabbitmq
      - rabbitmq_dlq
    volumes:
      - ./backend/src:/app  # temporary, to debug
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "100m"
    networks:
      - development_network
    restart: always

  backend_tests:
    build:
      context: ./backend
      dockerfile: Dockerfile-tests
    env_file:
      - ./backend/tests/.env
    depends_on:
      - backend
    networks:
      - development_network

  # region Autentication
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
      - ./.env:/opt/app/.env
    expose:
      - "5001"
    networks:
      - development_network
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15.1
    container_name: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
      - ./sqlite_to_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - development_network
    restart: always

  redis:
    image: redis:7.0.5
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - development_network
  # endregion

  # region UGC
  mongo:
    container_name: mongosingle
    image: mongo:6.0
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/tmp/mongo_single/data1:/data/db
    networks:
      - development_network
    restart: always
  # endregion

  # region ELK
  logstash:
    image: logstash:7.10.1
    env_file:
      - ./.env
    environment:
      XPACK_MONITORING_ENABLED: "true"
    expose:
      - "5043/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
      - ./tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf
    networks:
      - development_network

  elasticsearch:
    image: elasticsearch:7.10.1
    healthcheck:
      test: curl -s http://${ES_HOST} >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    expose:
      - "9200"
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    networks:
      - development_network

  kibana:
    image: kibana:7.10.1
    expose:
      - "5601"
    depends_on:
      - elasticsearch
    networks:
      - development_network
  # endregion
  nginx:
    image: nginx:1.23.2
    container_name: nginx_backend
    env_file:
      - ./.env
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:${LOGSTASH_PORT}
        tag: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - development_network
    restart: always

  #region Notification
  notificator:
    build:
      context: notification/notificator/
      dockerfile: Dockerfile
    depends_on:
      - notificator_postgres
      - rabbitmq
      - rabbitmq_dlq
     # TODO add permament folder to store file patterns
    networks:
      - development_network
    env_file:
       - ".env"
    restart: always

  notificator_postgres:
    image: postgres:15.1
    expose:
      - "5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${NOTIFICATION_PG_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_PG_PASSWORD}
      POSTGRES_DB: notification
    networks:
      - development_network
    volumes:
      - ./notification/notificator/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./notification_data:/var/lib/postgresql/data
    restart: always

  events_consumer:
    container_name: 'events_consumer'
    build:
      context: ./notification/events_consumer
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    networks:
      - development_network
    restart: always

  events_consumer_dlq:
    container_name: 'events_consumer_dlq'
    build:
      context: ./notification/events_consumer
    env_file:
      - ./.env
    environment:
      BROKER_HOST: ${BROKER_HOST_DLQ}
    depends_on:
      - rabbitmq_dlq
    networks:
      - development_network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - development_network
    restart: always

  rabbitmq_dlq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq_dlq'
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./rabbitmq_dlq/:/var/lib/rabbitmq/
      - ./rabbitmq_dlq/log/:/var/log/rabbitmq/
    networks:
      - development_network
    restart: always

  #endregion
  # Test for notification:
  tests:  # TODO To another file?
    build:
      context: notification/tests/
      dockerfile: Dockerfile
    depends_on:
      - notificator_postgres
      - events_consumer
    networks:
      - development_network
    env_file:
      - ".env"
  # region Profiles
  profiles_db:
    image: postgres:15.1
    expose:
      - "5434"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PROFILES_PG_USER}
      POSTGRES_PASSWORD: ${PROFILES_PG_PASSWORD}
      POSTGRES_DB: profiles
    networks:
      - development_network
    volumes:
      - ./profiles/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./profiles_data:/var/lib/postgresql/data
    restart: always

  profiles_service:
    build:
      context:
        ./profiles
    env_file:
      - ./.env
    environment:
      - RUN_MODE=GRPC
    expose:
      - "50051" # ${PROFILES_SERVICE_PORT}"
    depends_on:
      - profiles_db
    volumes:
      - ./profiles/src:/app  # temporary, to debug
    networks:
      - development_network
    restart: always

  profiles_tests:
    build:
      context: ./profiles
      dockerfile: Dockerfile-tests
    env_file:
      - ./.env
    depends_on:
      - profiles_service
    networks:
      - development_network
    # endregion

  etl_films:
    container_name: etl_async_api
    build:
      context: etl_films/postgres_to_es
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - development_network

  admin_panel:
    container_name: admin_panel_async_api
    build:
      context: admin-panel/movies
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: always
    volumes:
      - ./.env:/opt/app/.env
      - ./admin-panel/movies/static:/opt/app/static
    depends_on:
      - postgres
    networks:
      - development_network

networks:
  development_network:
    name: development_network
    external: true